SCREEN_SIZE = (SCREEN_SIZE_X, SCREEN_SIZE_Y) = (1280, 720)
DRAW_SCREEN_SIZE = (DRAW_SCREEN_SIZE_X, DRAW_SCREEN_SIZE_Y) = (320, 180)
STANDARD_FRAMERATE = 60
FRAMERATE = 60
MAP_SIZE = (MAP_SIZE_X, MAP_SIZE_Y) = (50, 25)
TILE_SIZE = 16
MAP_SIZE_PX = (MAP_SIZE_PX_X, MAP_SIZE_PX_Y) = (MAP_SIZE_X * TILE_SIZE, MAP_SIZE_Y * TILE_SIZE)
CAMERA_OFFSET_MOVE_AREA = 10
CAMERA_OFFSET_SPEED = 3
CAMERA_SMOOTH = 5
OBSTACLES_AMOUNT = 300