SCREEN_SIZE = (SCREEN_SIZE_X, SCREEN_SIZE_Y) = (1280, 720)
DRAW_SCREEN_SIZE = (DRAW_SCREEN_SIZE_X, DRAW_SCREEN_SIZE_Y) = (320, 180)
STANDARD_FRAMERATE = 60
FRAMERATE = 60
TILE_SIZE = 16
CAMERA_OFFSET_MOVE_AREA = 10
CAMERA_OFFSET_SPEED = 3
CAMERA_SMOOTH = 10
SPRITE_SIZE = 32
ANIMATION_LEN = 5
ANIMATION_NAMES = ('walk', 'fight')
ANIMATION_DIRECTIONS = ('top','right','bot')
ANIMATION_SPEED = 10 # frames per second
ROUND_LEN = 500
SHOW_GRID = False
SHOW_OBSTACLES_AREA = False
SHOW_SOLDIERS_REAL_POS = False
SHOW_TURRETS_REAL_POS = False
PARTICLE_DIRECTION_PRECISION = 100
STANDARD_PARTICLE_TIME = 10 # * 10
STANDARD_PARTICLE_SPEED = 3
STANDARD_PARTICLE_SIZE = 1
STANDARD_PARTICLE_ACC = 0.95
